# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_act": "10_tastenet_mnl.ipynb",
         "ChoiceFlex": "10_tastenet_mnl.ipynb",
         "Utility": "10_tastenet_mnl.ipynb",
         "TasteParams": "10_tastenet_mnl.ipynb",
         "ChoiceDataset": "10_tastenet_mnl.ipynb",
         "getAttribute": "10_tastenet_mnl.ipynb",
         "selectZ": "10_tastenet_mnl.ipynb",
         "say_hello": "93_MNL_from_scratch.ipynb",
         "MNL": "94_pytorch_MNL_example.ipynb",
         "load_model": "94_pytorch_MNL_example.ipynb",
         "build_model": "94_pytorch_MNL_example.ipynb"}

modules = ["MNL_benchmark.py",
           "tastenet_mnl.py",
           "statsmodels_intro.py",
           "statsmodels_MNL.py",
           "MNL_from_scratch.py",
           "pytorch_MNL_example.py"]

doc_url = "https://danhphan.github.io/choicenet/"

git_url = "https://github.com/danhphan/choicenet/tree/master/"

def custom_doc_links(name): return None
