# AUTOGENERATED! DO NOT EDIT! File to edit: 03_pytorch_discrete_choice.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
# Py3 Built-in module for type-hint annotations
from typing import Dict, Tuple, List, Callable, Optional
# Third-party modules for:
# class definition
import attr
# Optimization
import scipy.optimize as opt
# Numerical computation
import torch
import torch.nn as nn
import numpy as np
# Utility functions for pytorch optimization
import botorch.optim.numpy_converter as numpy_converter
import botorch.optim.utils as optim_utils
from botorch.optim.numpy_converter import TorchAttr
# Input/Output of data
import pandas as pd