# AUTOGENERATED! DO NOT EDIT! File to edit: 02_statsmodels_MNL_swissmetro.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'